/**
 * Generated by scripts/convert-tokens.ts from apps/app globals.css
 * (the design-system source of truth). sRGB-converted for RN runtime.
 * Regenerate after any palette change — never hand-edit values.
 */

/** The one accent: strong / accent-foreground / soft tint / accent-ink, per
 *  scheme. Neutral monochrome — the same accent apps/app uses (globals.css
 *  `--a-*`). There is no accent picker. */
export const ACCENT: Record<
  "light" | "dark",
  { strong: string; fg: string; soft: string; ink: string }
> = {
  light: {
    strong: "#191b1d",
    fg: "#fafafa",
    soft: "rgba(25, 27, 29, 0.07)",
    ink: "#303337",
  },
  dark: {
    strong: "#e8e8e8",
    fg: "#0d0d0d",
    soft: "rgba(255, 255, 255, 0.1)",
    ink: "#d7d7d7",
  },
};

export const TOKENS: Record<"light" | "dark", Record<string, string>> = {
  light: {
    background: "#fcfcfc",
    foreground: "#0a0a0a",
    card: "#ffffff",
    cardForeground: "#0a0a0a",
    secondary: "#f5f5f5",
    secondaryForeground: "#171717",
    muted: "#f5f5f5",
    mutedForeground: "#737373",
    destructive: "#dc2527",
    destructiveForeground: "#fcfcfc",
    success: "#219761",
    warning: "#ce871b",
    border: "#e5e5e5",
    input: "#e5e5e5",
  },
  dark: {
    background: "#0a0a0a",
    foreground: "#fafafa",
    card: "#171717",
    cardForeground: "#fafafa",
    secondary: "#262626",
    secondaryForeground: "#fafafa",
    muted: "#262626",
    mutedForeground: "#a1a1a1",
    destructive: "#ff6467",
    destructiveForeground: "#fcfcfc",
    success: "#45bf82",
    warning: "#efac44",
    border: "rgba(255, 255, 255, 0.1)",
    input: "rgba(255, 255, 255, 0.14)",
  },
};
